monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "php://stderr"
                level: debug
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!doctrine", "!console"]
#                channels: ["!event", "!doctrine", "!console"]

when@prod:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: info
#                excluded_http_codes: [404, 405]
                buffer_size: 300 # How many messages should be saved? Prevent memory leaks
