version: "3.5"

services:
  messenger:
    build:
      context: .docker/app
      args:
        - uuid=${CURRENT_UID:-1000}
    working_dir: /var/www
    depends_on:
      - app
    volumes:
      - .:/var/www:cached
    networks:
      - default
    command: php bin/console messenger:consume

  app:
    build:
      context: .docker/app
      args:
        - uuid=${CURRENT_UID:-1000}
        - without_xdebug=1
    working_dir: /var/www
    volumes:
      - .:/var/www:cached
    networks:
      - default
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
      XDEBUG_CONFIG: "client_host=host.docker.internal" # change to docker.for.win.localhost if on Windows without WSL
      XDEBUG_SESSION: "PHPSTORM"

  nginx:
    image: nginx
    ports:
      - "666:80" # http
    volumes:
      - ./:/var/www:cached
      - .docker/nginx/conf.d:/etc/nginx/conf.d
      - .docker/nginx/cert:/etc/nginx/cert:ro
    depends_on:
      - app
    networks:
      - default

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    networks:
      - default
    volumes:
    - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
