controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

spatricius.slack_unfurl:
    resource: '@SpatriciusSlackUnfurlBundle/Resources/config/routes.yaml'
